Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# In order to configure the MEDIA_URL we need the following (our statics urls):
from django.conf import settings
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('applications.category.urls')),
    path('account/', include('applications.accounts.urls')),
    path('', include('applications.store.urls')),
    path('cart/', include('applications.carts.urls')),
]

urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/accounts/urls.py
from django.urls import path
# Local views
from . import views

# Naming the whole urlpatterns
app_name = 'account_app'
# The base URL is declared in the main urls.py file as 'account/'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # If a user try to access to accounts/ url it'll show an error message
    # To avoid that, we can stablish a default url for this
    path('', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgot-password'),
    
    # Reset Password Process: Validate the user credentials.
    path('resetPasswordValidate/<uidb64>/<token>/', views.resetPasswordValidate, name='reset-password-validate'),
    # Reset Password Process: Reset the password
    path('resetPassword/', views.resetPassword, name='reset-password'),
]

applications/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from .managers import AccountManager

# Custom User Model
class Account(AbstractBaseUser):
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    username        = models.CharField(max_length=50, unique=True)
    email           = models.EmailField(max_length=100, unique=True)
    phone_number    = models.CharField(max_length=50)
    # Required fields for the AbstractBaseUser class when we are creating a custom user model
    date_joined     = models.DateTimeField(auto_now_add=True)
    last_login      = models.DateTimeField(auto_now_add=True)
    # is_staff: if the user has permission to access to the admin site
    is_staff        = models.BooleanField(default=False)
    # is_active: if the user account can be used for authentication
    # A user must verify their email address to activate their account (is_active=True).
    # If the account doesn't get activated, the user would not be able to access to the application.
    is_active       = models.BooleanField(default=False)
    is_superuser    = models.BooleanField(default=False)
    # We have to indicate with which field the user will log in into our application
    USERNAME_FIELD = 'email'
    # Extra fields that are required for our model
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']
    # Linking the manager to our model
    objects = AccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.email

    # If the user is superuser, then has the permission to do any changes
    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True

applications/accounts/forms.py
from django import forms
from .models import Account

# Creating a form that depends on a model
class RegistrationForm(forms.ModelForm):
    # Custom fields are not explicit declared in our model, so the value
    # we give to them won't be saved in the dabase, at least we want it. 
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }))

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']

    # This function initializes the form before it gets sent to the template
    def __init__(self, *args, **kwargs):
        # self.fields is populated after __init__ of ModelForm has executed, so before
        # we make any changes to self.fields, we have to call superclass __init__ 
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        # Looping through all the form fields and assign them the same class
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
    
    # When are performing a validation on more than one field at a time, the 
    # best approach is using the clean method
    def clean(self):
        # Calling the superclass clean() method in order to obtain the cleaned_data
        # that has all the form fields that have been previously validated. 
        cleaned_data = super(RegistrationForm, self).clean()
        password         = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        # Verifying whether the passwords match or not
        if password != confirm_password:
            raise forms.ValidationError('Passwords have to match!')

applications/accounts/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
# Import for adding Django messages to our view
from django.contrib import messages
from django.contrib.auth import authenticate
# We do this in order to avoid a TypeError between the functions that have the same name
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Login Decorator
from django.contrib.auth.decorators import login_required
# Django sites framework
from django.contrib.sites.shortcuts import get_current_site
# Imports for the Verification Email Process
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
# Local Models
from .models import Account
# External Models
from applications.carts.models import Cart, CartItem
# Local Forms
from .forms import RegistrationForm
# External View Functions
from applications.carts.views import _get_session_id
# Third Party Apps
import requests


# View: Register a new user in our system
def register(request):

    if request.method == 'POST':
        # Creating an instance of the form with the user-data
        form = RegistrationForm(request.POST)
        # Valitaing the form to access to the cleaned_data attribute
        if form.is_valid():
            # Once the form is valid, we can access to the cleaned_data dictionary
            first_name   = form.cleaned_data['first_name']
            last_name    = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email        = form.cleaned_data['email']
            password     = form.cleaned_data['password']
            # Assign a username based on the email
            username = email.split('@')[0]
            # Creating the user account
            user = Account.objects._create_user(
                first_name=first_name, 
                last_name=last_name, 
                email=email, 
                username=username, 
                password=password
            )
            # Adding the phone number to the user instance
            user.phone_number = phone_number
            user.save()
            """ USER ACTIVATION PROCESS
            Retrieving the current Site object (domain and name) based on the request
            That's necessary because the default domain is localhost, but when the site
            is on production side, it will change """
            current_site = get_current_site(request)
            email_subject = 'Please activate your account'
            email_body = render_to_string('accounts/email_verification.html', {
                'user': user,
                'domain': current_site,
                # We must enconding the user primary key because we're going to send 
                # it throuhg the URL for the activation process when the user start
                # the verification process (click on the link we sent to his email)
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                # Creating a token (verification code) for this particular user, the
                # generated token is actually a one-use one and exclusive for this user.
                'token': default_token_generator.make_token(user) 
            })

            email_recipient = email
            # Sending an email to the user email
            send_email = EmailMessage( email_subject, email_body, to=[email_recipient])
            send_email.send()

            # If everything went well, we display a proper message to the user
            # messages.success(request, 'Registration successful.')
            return redirect(f'/account/login/?command=verification&email={email}')
        
    else:
        # Assigning the created form to the view and render it to the template
        form = RegistrationForm()
    
    # Passing the whole form to our template
    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)

# View: Login authentication
def login(request):
    print(f'POST-LOGIN: {request.POST}')
    if request.method == 'POST':
        # Retrieving the email and the password sent in the URL by the POST request
        email    = request.POST['email']
        password = request.POST['password']
        # Verifying if the user email and password are valid
        user = authenticate(email=email, password=password)
        # If the user gets authenticated successfully in our system, then
        if user is not None:
            try:
                # Before the login process, we have to check if there're already CartItems added
                cart = Cart.objects.get(cart_id=_get_session_id(request))
                # Verifying if the current Cart has CartItems
                is_any_cart_item = CartItem.objects.filter(cart=cart).exists()

                if is_any_cart_item:
                    # Getting all the CartItems inside the current Cart
                    cart_items = CartItem.objects.filter(cart=cart)
                    # Product: Shirt, Variations: Blue and Large
                    cart_variations = []
                    cart_indices = []
                    # Getting all the CartItem variations form the current Cart
                    for cart_item in cart_items:
                        variations = cart_item.variations.all()
                        # Where the variation gets positioned in list, the index will be in the same position
                        cart_variations.append(list(variations))
                        cart_indices.append(cart_item.id)
                        
                    # Getting all the CartItem variations from all the user products that's about to login
                    user_items = CartItem.objects.filter(user=user)
                    # Obtaining all the variations and the indices that all the user_items found have
                    user_variations  = []
                    existing_indices = []
                    # Adding all the user_item variations inside their corresponding list
                    for user_item in user_items:
                        # Saving the variations of that particular CartItem
                        user_variations.append(list(user_item.variations.all()))
                        # Saving the index of that particular CartItem 
                        existing_indices.append(user_item.id)

                    # We have to compare the cart_variations (current Cart) with the user_variations (current User)
                    for cart_variation in cart_variations:
                        if cart_variation in user_variations:
                            # Getting the index of the "cart_variation" inside the list of user_variations
                            index = user_variations.index(cart_variation)
                            user_item_id = existing_indices[index]
                            # Finally we have to retrive that CartItem from the user Cart and increase its quantity
                            user_item = CartItem.objects.get(id=user_item_id) 
                            user_item.quantity += 1
                            user_item.save()
                        else:
                            print(f"CURRENT VARIATIONS LIST: {cart_variation}")
                            index = cart_variations.index(cart_variation)
                            cart_item_id = cart_indices[index]
                            cart_item = CartItem.objects.get(id=cart_item_id)
                            cart_item.user = user
                            cart_item.save()

            # The except gets executed if we don't have any CartItem inside the Cart
            except:
                pass
            
            auth_login(request, user)
            messages.success(request, 'You are now logged in')
            # If the user comes from the "/cart/checkout/" it means the
            # he already has products inside his Cart
            # HTTP_REFERER: It returns the page from what you came from 
            previous_url = request.META.get('HTTP_REFERER')
            print(f'PREVIOUS URL: {previous_url}')
            try:
                # From this url: http://127.0.0.1:8000/account/login/?next=/cart/checkout/
                # We store inside 'query': next=/cart/checkout/ 
                query = requests.utils.urlparse(previous_url).query
                key, url = query.split('=')
                params = {
                    key: url
                }
                
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('account_app:dashboard')

        else:
            messages.error(request, 'Invalid login credentials')
            return  redirect('account_app:login')

    return render(request, 'accounts/login.html')
    
""" We only can logout if we're already login in the system
Otherwise, we cannot access to this view, so to ensure that
this situation happens, we use a decorator..."""

@login_required(login_url= 'account_app:login')
def logout(request):
    auth_logout(request)
    messages.success(request, 'You are logged out')
    return redirect('account_app:login')

# View for activating a user account, it sets the is_active to True
def activate(request, uidb64, token):
    
    try:
        # Decoding the user primary key
        uid = urlsafe_base64_decode(uidb64).decode()
        # When we're using a custom Manager objects and if we want
        # to use the default Manager that Django creates instead...
        user = Account._default_manager.get(pk=uid)

    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            <aside class="col-md-3">
                <!--   SIDEBAR   -->
                <ul class="list-group">
                    <a class="list-group-item active" href="#"> My order history </a>
                    <a class="list-group-item" href="#"> Transactions </a>
                    <a class="list-group-item" href="#"> Return and refunds </a>
                    <a class="list-group-item" href="#">Settings </a>
                    <a class="list-group-item" href="#"> My Selling Items </a>
                    <a class="list-group-item" href="#"> Received orders </a>
                </ul>
                <br>
                <a class="btn btn-light btn-block" href="{% url 'account_app:logout' %}"> <i
                        class="fa fa-power-off"></i> <span class="text">Log
                        out</span> </a>
                <!--   SIDEBAR .//END   -->
            </aside>
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
                        <span>Order Date: 16 December 2018</span>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <h6 class="text-muted">Delivery to</h6>
                                <p>Michael Jackson <br>
                                    Phone +1234567890 Email: myname@pixsellz.com <br>
                                    Location: Home number, Building name, Street 123, Tashkent, UZB <br>
                                    P.O. Box: 100123
                                </p>
                            </div>
                            <div class="col-md-4">
                                <h6 class="text-muted">Payment</h6>
                                <span class="text-success">
                                    <i class="fab fa-lg fa-cc-visa"></i>
                                    Visa **** 4216
                                </span>
                                <p>Subtotal: $356 <br>
                                    Shipping fee: $56 <br>
                                    <span class="b">Total: $456 </span>
                                </p>
                            </div>
                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <tr>
                                <td width="65">
                                    <img src="../images/items/1.jpg" class="img-xs border">
                                </td>
                                <td>
                                    <p class="title mb-0">Product name goes here </p>
                                    <var class="price text-muted">USD 145</var>
                                </td>
                                <td> Seller <br> Nike clothing </td>
                                <td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#"
                                        class="btn btn-light"> Details </a> </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../images/items/2.jpg" class="img-xs border">
                                </td>
                                <td>
                                    <p class="title mb-0">Another name goes here </p>
                                    <var class="price text-muted">USD 15</var>
                                </td>
                                <td> Seller <br> ABC shop </td>
                                <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#"
                                        class="btn btn-light"> Details </a> </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../images/items/3.jpg" class="img-xs border">
                                </td>
                                <td>
                                    <p class="title mb-0">The name of the product goes here </p>
                                    <var class="price text-muted">USD 145</var>
                                </td>
                                <td> Seller <br> Wallmart </td>
                                <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#"
                                        class="btn btn-light"> Details </a> </td>
                            </tr>
                        </table>
                    </div> <!-- table-responsive .end// -->
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}

templates/accounts/email_verification.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on the link below to confirm your registration.
http://{{domain}}{% url 'account_app:activate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}

templates/accounts/forgotPassword.html
{% extends 'base.html' %}


{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">
    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 500px; margin-top:100px;">
        <div class="card-body">
            {% include 'includes/alerts.html' %}
            <h4 class="card-title mb-4">Forgot Password</h4>
            <form action="{% url 'account_app:forgot-password' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email Address" name="email">
                </div>
                <!-- form-group// -->
                <div class="form-group">
                    <a href="{% url 'account_app:login' %}" class="float-right">Got password? Login</a>
                </div>
                <!-- form-group form-check .// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Submit </button>
                </div> <!-- form-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'account_app:register' %}">Sign up</a></p>
    <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">
    <!-- If the user comes from the registration process, it means that he have to
    valitade it's account in order to activate it, for doing that we have to show
    a different template and retrieve the value of "command" sent in the browser URL 
    via GET request -->
    {% if request.GET.command == 'verification' %}
    <div class="container mx-auto alert alert-info text-center" role="alert"
        style="max-width: 1024px; margin-top:100px;">
        Thank you for registering with us. We have sent you a verification email to your email address:
        {{ request.GET.email }}
        <br><br>
        Already verified? <a href="{% url 'account_app:login' %}">Login</a>
    </div>
    {% else %}
    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
            {% include 'includes/alerts.html' %}
            <h4 class="card-title mb-4">Sign in</h4>
            <form action="{% url 'account_app:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email Address" name="email">
                </div> <!-- form-group// -->
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" name="password">
                </div> <!-- form-group// -->

                <div class="form-group">
                    <a href="{% url 'account_app:forgot-password' %}" class="float-right">Forgot password?</a>

                </div> <!-- form-group form-check .// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Login </button>
                </div> <!-- form-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'account_app:register' %}">Sign up</a></p>
    <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    {% endif %}

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}


{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
    <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
        <article class="card-body">
            <!-- Including our custom Django messages -->
            {% include 'includes/alerts.html' %}
            <header class="mb-4">
                <h4 class="card-title">Sign up</h4>
            </header>
            <form action="{% url 'account_app:register' %}" method="POST">
                {% csrf_token %}

                <div class="form-row">
                    <div class="col form-group col-md-6">
                        <label>First name</label>
                        {{ form.first_name }}
                    </div> <!-- form-group end.// -->
                    <div class="col form-group col-md-6">
                        <label>Last name</label>
                        {{ form.last_name }}
                    </div> <!-- form-group end.// -->
                </div> <!-- form-row end.// -->
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Email Address</label>
                        {{form.email}}
                    </div> <!-- form-group end.// -->
                    <div class="form-group col-md-6">
                        <label>Phone Number</label>
                        {{form.phone_number}}
                    </div> <!-- form-group end.// -->
                </div> <!-- form-row.// -->
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Create password</label>
                        {{ form.password }}
                    </div> <!-- form-group end.// -->
                    <div class="form-group col-md-6">
                        <label>Repeat password</label>
                        {{ form.confirm_password }}
                    </div> <!-- form-group end.// -->
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Register </button>
                </div> <!-- form-group// -->

                <!-- This method will indicate an error based on the restrictions we inflict
                For instance, it can be that one Account already exists with this email -->
                {{ form.email.errors }}
                <!-- This method returns the list of errors from Form.errors that aren’t associated 
                with a particular field. This includes ValidationErrors that are raised in Form.clean()  -->
                {{ form.non_field_errors }}
            </form>

            </form>
        </article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'account_app:login' %}">Log In</a></p>
    <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->

</section>

{% endblock content %}

templates/accounts/resetPassword.html
{% extends 'base.html' %}


{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">
    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 500px; margin-top:100px;">
        <div class="card-body">
            {% include 'includes/alerts.html' %}
            <h4 class="card-title mb-4">Reset Password</h4>
            <form action="{% url 'account_app:reset-password' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="New password" name="password">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Confirm your password"
                        name="confirm_password">
                </div>
                <!-- form-group// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Reset </button>
                </div> <!-- form-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'account_app:register' %}">Sign up</a></p>
    <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on the link below to reset your password.
http://{{domain}}{% url 'account_app:reset-password-validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}