Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# In order to configure the MEDIA_URL we need the following (our statics urls):
from django.conf import settings
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('applications.category.urls')),
    path('account/', include('applications.accounts.urls')),
    path('', include('applications.store.urls')),
    path('cart/', include('applications.carts.urls')),
]

urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/carts/urls.py
from django.urls import path
from . import views 

# Naming the whole urlpatterns
app_name = 'cart_app'

urlpatterns = [
    # The base URL is declared in the main urls.py file as 'cart/'
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('decrease_cart/<int:product_id>/<int:cart_item_id>/', views.decrease_cart, name='decrease_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
     # URL for Checkout
    path('checkout/', views.checkout, name='checkout')
]

applications/store/urls.py
from django.urls import path
from . import views

# Naming the urlpatterns as a whole
app_name = 'store_app'

urlpatterns = [
    # We have two URLs that occupy the same view
    path('store/', views.store, name='store'),
    # We're sending to our view the 'category_slug' parameter which is sent in the URL 
    path('store/category/<slug:category_slug>/', views.store, name='products_by_category'),
    # URL for the product detail
    path('store/category/<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'),
    # URL for performing searching request
    path('store/search/', views.search_product, name='search_product'),
]

applications/carts/models.py
from django.db import models

# External Models
from applications.accounts.models import Account
from applications.store.models import Product, Variation

# Create your models here.
class Cart(models.Model):
    # This cart_id will be stored in the Session Cookie as Session ID
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    # One Account can have many CardItems, but one CardItem is meant for one Account
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    # One Product can be (relationated to) in many CardItems
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # One CartItem can have many Variations and one Variation can belong to many CartItems
    variations = models.ManyToManyField(Variation, blank=True)
    # One Cart can have to many CartItems, but one CartItem must belong only to one Cart
    cart    = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity
 
    # To print an instance model (object), we can use the '__unicode__' method
    def __str__(self):
        return 'Cart: ' + str(self.cart.cart_id) + ': '+ self.product.product_name


    

applications/carts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, render, redirect
# Login Decorator
from django.contrib.auth.decorators import login_required
# Local Models
from .models import Cart, CartItem
# External Models
from applications.store.models import Product, Variation

# Private Function: Fetching the Session ID from a cookie on the browser
def _get_session_id(request):
    session_id = request.session.session_key
    if not session_id:
        session_id = request.session.create()
    # print(f'Session ID: {session_id}')
    return session_id


# View: Show the cart and all its items
def cart(request, cart_items=None):
    # Initializing all the variables
    total_price    = 0
    total_products = 0
    tax = 0
    grand_total = 0
    # This view gets executed everytime we invoke it using the 'redirect' function
    try:
        # Checking is the user is authenticated
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            # Retrieving the current cart associated with the current session_id
            cart = Cart.objects.get(cart_id=_get_session_id(request))
            # Filtering out all the products according to the current cart
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        # Computing the total price
        for cart_item in cart_items:
            total_price    += (cart_item.product.price * cart_item.quantity)
            total_products += cart_item.quantity
        # Tax of 2% applied in the final price
        tax = (2*total_price)/100
        # Calculating the grand total
        grand_total = total_price + tax

    except ObjectDoesNotExist:
        # Just ignore the cart and display an empty cart
        pass 
    
    # Defining our context dictionary 
    context = {
        'cart_items': cart_items,
        'total_price': total_price,
        'total_products': total_products,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'store/cart.html', context)

# View: Add to cart functionality
def add_to_cart(request, product_id):
    # Getting the current user
    current_user = request.user
    # Getting the product by the given product_id by the URL
    product = Product.objects.get(id=product_id)
    product_variations = []

    # Retrieving all the paramaters inside the browser URL sent by the user
    if request.method == 'POST':
        # print(f'add_to_cart | POST Request: {request.POST}')
        for variation_key in request.POST:
            variation_value = request.POST[variation_key]
            # Retrieving the variation object for one specific product, that matches with the data sent via POST method 
            try:
                # iexact is case-insensitive exact match  
                variation = Variation.objects.get(
                    product = product,
                    variation_category__iexact=variation_key, 
                    variation_value__iexact=variation_value)
                # Creating a variation's list that holds each product variation added to the current cart
                product_variations.append(variation)
            except:
                pass
            
    if current_user.is_authenticated:
        # Checking if the product sent in the URL is already in the user Cart or Not
        is_cart_item_in_cart = CartItem.objects.filter(user=current_user,product=product).exists() 

        # Adding the products to the user Cart
        if is_cart_item_in_cart:
            # Getting all the user CartItems that correspond to the product sent in the URL  
            cart_items = CartItem.objects.filter(user=current_user, product=product)
            # Obtaining all the variations and the indices that all the cart_items found have
            existing_variations = []
            existing_indices    = []
            # We have to check if the variation of the product is already added in the Cart or not
            for cart_item in cart_items:
                existing_variations.append(list(cart_item.variations.all()))
                existing_indices.append(cart_item.id)

            print(f"Current variation: {product_variations}")
            print(f"Existing variations: {existing_variations}")

            # If the current variations 'product_variations' is in the existing_variations
            # Like "Blue and Large" exists in the existing_variations
            if product_variations in existing_variations:
                # Then, we have to retrieve the index of the CartItem that holds 'product_variations'
                index = existing_variations.index(product_variations)
                cart_item_id = existing_indices[index] 
                # Finally we have to retrive that CartItem from the Cart and increase its quantity
                cart_item = CartItem.objects.get(product=product,id=cart_item_id)
                cart_item.quantity += 1
                cart_item.save()

            else:
                # We have to create a new instance of CartItem for this product with its new variation
                cart_item = CartItem.objects.create(
                    user = current_user,
                    product = product,
                    quantity = 1,
                )
                # Checking if the product_variations list is empty or not
                if product_variations:
                    # Adding the variations for the product selected by the user
                    cart_item.variations.add(*product_variations)
                # Saving the CartItem in the database
                cart_item.save()

        # If there's the first time that we add the product in the user Cart
        else:
            # Creating and adding the item in our cart
            cart_item = CartItem.objects.create(
                user = current_user,
                product = product,
                quantity = 1,
            )

            if product_variations:
                # Many to Many filed uses the 'add' method to add elements to it
                cart_item.variations.add(*product_variations)
            # Saving the CartItem in the database 
            cart_item.save()

    # If there's an anonymous user
    else:
        # If there's already a cart saved (Session ID was created)
        try: 
            # The cart_id will be equals to the Session ID stored on the browser
            cart = Cart.objects.get(cart_id=_get_session_id(request))

        # If the Cart doesn't exist, meaning there's no session ID created 
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _get_session_id(request)
            )
            # Saving the cart in the database
            cart.save()

        # Checking if the product sent in the URL is already in the Cart or Not
        is_cart_item_in_cart = CartItem.objects.filter(product=product, cart=cart).exists() 

        # Adding the products to the cart
        if is_cart_item_in_cart:
            # Getting all the CartItems from the Cart that correspond to the product sent in the URL  
            cart_items = CartItem.objects.filter(product=product, cart=cart)
            # Obtaining all the variations and the indices that all the cart_items found have
            existing_variations = []
            existing_indices    = []
            # We have to check if the variation of the product is already added in the Cart or not
            for cart_item in cart_items:
                existing_variations.append(list(cart_item.variations.all()))
                existing_indices.append(cart_item.id)

            print(f"Current variation: {product_variations}")
            print(f"Existing variations: {existing_variations}")

            # If the current variations 'product_variations' is in the existing_variations
            # Like "Blue and Large" exists in the existing_variations
            if product_variations in existing_variations:
                # Then, we have to retrieve the index of the CartItem that holds 'product_variations'
                index = existing_variations.index(product_variations)
                cart_item_id = existing_indices[index] 
                # Finally we have to retrive that CartItem from the Cart and increase its quantity
                cart_item = CartItem.objects.get(product=product,id=cart_item_id)
                cart_item.quantity += 1
                cart_item.save()

            else:
                # We have to create a new instance of CartItem for this product with its new variation
                cart_item = CartItem.objects.create(
                    product = product,
                    cart = cart,
                    quantity = 1,
                )
                # Checking if the product_variations list is empty or not
                if product_variations:
                    # Adding the variations for the product selected by the user
                    cart_item.variations.add(*product_variations)
                # Saving the CartItem in the database
                cart_item.save()

        # If there's the first time that we add the product in the current cart
        else:
            # Creating and adding the item in our cart
            cart_item = CartItem.objects.create(
                product = product,
                cart = cart,
                quantity = 1,
            )

            if product_variations:
                # Many to Many filed uses the 'add' method to add elements to it
                cart_item.variations.add(*product_variations)
            # Saving the CartItem in the database 
            cart_item.save()

    return redirect('cart_app:cart')

# View: Decrease the aquantity for a product form cart functionality
def decrease_cart(request, product_id, cart_item_id):

    # Getting the product by the product_id

applications/store/views.py
from django.shortcuts import render, get_object_or_404
# Logic operation OR in queries
from django.db.models import Q
# Paginator Functionality
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
# Local Models
from .models import Product
# External Models
from applications.category.models import Category
from applications.carts.models import CartItem
# External Functions
from applications.carts.views import _get_session_id

# View: Filter products out by the given category
def store(request, category_slug=None):
    # Default values
    category = None
    products = None

    # If the user want to search the products by a category, then
    if category_slug != None:
        # Getting the category where the slug field from Category's model is equals to 'category_slug'
        category = get_object_or_404(Category, slug=category_slug)
        # Retrieving all the product according to the given category
        products = Product.objects.filter(category=category, is_available=True).order_by('id')

    else:   
        # Retrieving only the products that are available
        products = Product.objects.filter(is_available=True).order_by('id')
        # If we want to use a pagination, we have to order the QuerySet result

    # The Paginator class returns an "page_obj", we'll show 6 products per page
    paginator = Paginator(products, 6)
    # The URL has the form: url/?page=num_page, so we're retrieving the number of 'page'
    page = request.GET.get('page')
    # Getting all the products contained in the number of page given by the URL
    paged_products = paginator.get_page(page)
    # Counting the number of products that we have
    products_count = products.count()

    # Passing the context to the render method, will make our products available inside the template
    context = {
        'products': paged_products,
        'products_count': products_count,
    }

    # The store directory is created inside our template's directory
    return render(request,'store/store.html', context)
 
# View: Product Detail
def product_detail(request, category_slug, product_slug):
    try:
        # Retrieving a product by the given category and the given slug of the product
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        # Verifying if the product is already in one cart
        is_in_cart = CartItem.objects.filter(product=single_product, cart__cart_id=_get_session_id(request)).exists()
        # If the QuerySet contains any result, then the function 'exists' returns True, otherwise False

    # If the product doesn't exist
    except Exception as e:
        raise e

    context = {
        'single_product' : single_product,
        'is_in_cart': is_in_cart,
    }

    return render(request, 'store/product_detail.html', context)

# View: Searching products by the given keyword in the URL
def search_product(request):
    print(f'Search product | GET request: {request.GET}' )
    products = None
    products_count = 0
    # We have to recieve the <form> data that comes in the URL
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        # If the keyword is not an empty str ''
        if keyword:
            # Getting all the products where their description or name match wich the keyword sent by the user
            products = Product.objects.filter( 
                Q(product_name__icontains=keyword) | Q(description__icontains=keyword) 
            ).order_by('-creation_date')
            # Counting the number of products that we have
            products_count = products.count()

    context = {
        'products': products,
        'products_count': products_count,
    }

    return render(request,'store/store.html', context)

templates/store/cart.html
{% extends 'base.html' %} {% load static %}
<!-- Main content -->
{% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <!-- If there's no cart items -->
    {% if not cart_items %}
    <!-- Message -->
    <h2 class="text-center">Your Shopping cart is empty</h2>
    <br />
    <div class="text-center">
      <a href="{% url 'store_app:store' %}" class="btn btn-primary">Continue Shopping</a>
    </div>
    {% else %}
    <div class="row">
      <aside class="col-lg-9">
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"></th>
              </tr>
            </thead>
            <tbody>
              {% for cart_item in cart_items %}
              <tr>
                <td>
                  <figure class="itemside align-items-center">
                    <div class="aside">
                      <img src="{{ cart_item.product.images.url }}" class="img-sm" />
                    </div>
                    <figcaption class="info">
                      <a href="{{ cart_item.product.get_url }}"
                        class="title text-dark">{{cart_item.product.product_name}}</a>
                      <p class="text-muted small">
                        <!-- List all the products variations -->
                        {% for variation in cart_item.variations.all %}
                        {{variation.variation_category | capfirst}} : {{variation.variation_value}}
                        <br />
                        {% endfor %}
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">

                        <a href="{% url 'cart_app:decrease_cart' cart_item.product.id cart_item.id %}"
                          class="btn btn-light" type="button" id="button-minus">
                          <i class="fa fa-minus"></i>
                        </a>


                      </div>
                      <input type="text" class="form-control" value="{{cart_item.quantity}}" />
                      <div class="input-group-append">
                        <form action="{% url 'cart_app:add_cart' cart_item.product.id %}" method="POST">
                          {% csrf_token %}
                          <!-- Looping through all the variations that the CartItem has, in order to
                          send to the server the following url: "?variation_category=variation_value" -->
                          {% for variation in cart_item.variations.all %}
                          <input type="hidden" name="{{ variation.variation_category }}"
                            value="{{ variation.variation_value }}">
                          {% endfor %}

                          <button type="submit" class="btn btn-light" id="button-plus">
                            <i class="fa fa-plus"></i>
                          </button>
                        </form>

                      </div>
                    </div>
                    <!-- input-group.// -->
                  </div>
                  <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">${{cart_item.sub_total}}</var>
                    <small class="text-muted">
                      ${{cart_item.product.price}} each
                    </small>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a href="{% url 'cart_app:remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-danger"
                    onclick="return confirm('Are you sure you want to delete this product from your cart')">
                    Remove</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <aside class="col-lg-3">
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              <dd class="text-right">${{total_price}}.00</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Tax:</dt>
              <dd class="text-right">${{tax}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Grand Total:</dt>
              <dd class="text-right text-dark b">
                <strong>${{grand_total}}</strong>
              </dd>
            </dl>
            <hr />
            <p class="text-center mb-3">
              <img src="{% static 'images/misc/payments.png' %}" height="26" />
            </p>
            <a href="{% url 'cart_app:checkout' %}" class="btn btn-primary btn-block">
              Checkout
            </a>
            <a href="{% url 'store_app:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
          </div>
          <!-- card-body.// -->
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
    </div>
    <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/store/checkout.html
{% extends 'base.html' %} {% load static %}
<!-- Main content -->
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="row">
            <aside class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title mb-4">Billing Address</h4>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <!-- Row Start -->
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">First Name</label>
                                    <input type="text" name="first_name" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Last Name</label>
                                    <input type="text" name="last_name" class="form-control" required>
                                </div>
                            </div>
                            <!-- Row End -->

                            <!-- Row Start -->
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Email</label>
                                    <input type="email" name="email" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Phone Number</label>
                                    <input type="text" name="phone" class="form-control" required>
                                </div>
                            </div>
                            <!-- Row End -->

                            <!-- Row Start -->
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Address Line 1</label>
                                    <input type="text" name="address_line_1" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Address Line 2</label>
                                    <input type="text" name="address_line_2" class="form-control">
                                </div>
                            </div>
                            <!-- Row End -->

                            <!-- Row Start -->
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">City</label>
                                    <input type="text" name="city" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">State</label>
                                    <input type="text" name="state" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Country</label>
                                    <input type="text" name="country" class="form-control" required>
                                </div>
                            </div>
                            <!-- Row End -->

                            <!-- Row Start -->
                            <div class="form-row">
                                <label for="">Order Note</label>
                                <textarea name="order_note" rows="2" class="form-control"></textarea>
                            </div>
                            <!-- Row End -->
                    </div>
                </div>
                <!-- card.// -->
            </aside>
            <!-- col.// -->
            <aside class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <!-- Table Start -->
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cart_item in cart_items %}
                                <tr>
                                    <td>
                                        <figure class="itemside align-items-center">
                                            <div class="aside">
                                                <img src="{{ cart_item.product.images.url }}" class="img-sm" />
                                            </div>
                                            <figcaption class="info">
                                                <a href="{{ cart_item.product.get_url }}"
                                                    class="title text-dark">{{cart_item.product.product_name}}</a>
                                                <p class="text-muted small">
                                                    <!-- List all the products variations -->
                                                    {% for variation in cart_item.variations.all %}
                                                    {{variation.variation_category | capfirst}} :
                                                    {{variation.variation_value}}
                                                    <br />
                                                    {% endfor %}
                                                </p>
                                            </figcaption>
                                        </figure>
                                    </td>
                                    <td>
                                        {{ cart_item.quantity }}
                                    </td>
                                    <td>
                                        <div class="price-wrap">
                                            <var class="price">${{cart_item.sub_total}}</var>
                                            <small class="text-muted">
                                                ${{cart_item.product.price}} each
                                            </small>
                                        </div>
                                        <!-- price-wrap .// -->
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <!-- Table End -->
                        <button type="submit" class="btn btn-primary btn-block">
                            Place Order
                        </button>
                        <a href="{% url 'store_app:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                        </form>
                    </div>
                    <!-- card-body.// -->
                </div>
                <!-- card.// -->
            </aside>
            <!-- col.// -->
        </div>
        <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->
    </div>
    <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}